/*
 * swagger说明文档　
 * 学习Swagger
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pml.sdsn.common.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Constraint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2022-08-25T14:33:24.122+08:00")
public class Constraint {
  @JsonProperty("includeNodes")
  private List<String> includeNodes = null;

  @JsonProperty("excludeNodes")
  private List<String> excludeNodes = null;

  @JsonProperty("excludeLinks")
  private List<String> excludeLinks = null;

  public Constraint includeNodes(List<String> includeNodes) {
    this.includeNodes = includeNodes;
    return this;
  }

  public Constraint addIncludeNodesItem(String includeNodesItem) {
    if (this.includeNodes == null) {
      this.includeNodes = new ArrayList<>();
    }
    this.includeNodes.add(includeNodesItem);
    return this;
  }

  /**
   * Get includeNodes
   * @return includeNodes
   **/
  @JsonProperty("includeNodes")
  @ApiModelProperty(value = "")
  public List<String> getIncludeNodes() {
    return includeNodes;
  }

  public void setIncludeNodes(List<String> includeNodes) {
    this.includeNodes = includeNodes;
  }

  public Constraint excludeNodes(List<String> excludeNodes) {
    this.excludeNodes = excludeNodes;
    return this;
  }

  public Constraint addExcludeNodesItem(String excludeNodesItem) {
    if (this.excludeNodes == null) {
      this.excludeNodes = new ArrayList<>();
    }
    this.excludeNodes.add(excludeNodesItem);
    return this;
  }

  /**
   * Get excludeNodes
   * @return excludeNodes
   **/
  @JsonProperty("excludeNodes")
  @ApiModelProperty(value = "")
  public List<String> getExcludeNodes() {
    return excludeNodes;
  }

  public void setExcludeNodes(List<String> excludeNodes) {
    this.excludeNodes = excludeNodes;
  }

  public Constraint excludeLinks(List<String> excludeLinks) {
    this.excludeLinks = excludeLinks;
    return this;
  }

  public Constraint addExcludeLinksItem(String excludeLinksItem) {
    if (this.excludeLinks == null) {
      this.excludeLinks = new ArrayList<>();
    }
    this.excludeLinks.add(excludeLinksItem);
    return this;
  }

  /**
   * Get excludeLinks
   * @return excludeLinks
   **/
  @JsonProperty("excludeLinks")
  @ApiModelProperty(value = "")
  public List<String> getExcludeLinks() {
    return excludeLinks;
  }

  public void setExcludeLinks(List<String> excludeLinks) {
    this.excludeLinks = excludeLinks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Constraint constraint = (Constraint) o;
    return Objects.equals(this.includeNodes, constraint.includeNodes) &&
        Objects.equals(this.excludeNodes, constraint.excludeNodes) &&
        Objects.equals(this.excludeLinks, constraint.excludeLinks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeNodes, excludeNodes, excludeLinks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Constraint {\n");

    sb.append("    includeNodes: ").append(toIndentedString(includeNodes)).append("\n");
    sb.append("    excludeNodes: ").append(toIndentedString(excludeNodes)).append("\n");
    sb.append("    excludeLinks: ").append(toIndentedString(excludeLinks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

