/*
 * vpn模型定义　
 * vpn模型
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pml.sdsn.common.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * LinkPath
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2022-08-11T15:53:03.751+08:00")
public class LinkPath {
  @JsonProperty("path")
  private List<String> path = null;

  @JsonProperty("delay")
  private Double delay = null;

  @JsonProperty("hop")
  private Long hop = null;

  @JsonProperty("metric")
  private Long metric = null;

  public LinkPath path(List<String> path) {
    this.path = path;
    return this;
  }

  public LinkPath addPathItem(String pathItem) {
    if (this.path == null) {
      this.path = new ArrayList<>();
    }
    this.path.add(pathItem);
    return this;
  }

  /**
   * Get path
   * @return path
   **/
  @JsonProperty("path")
  @ApiModelProperty(value = "")
  public List<String> getPath() {
    return path;
  }

  public void setPath(List<String> path) {
    this.path = path;
  }

  public LinkPath delay(Double delay) {
    this.delay = delay;
    return this;
  }

  /**
   * Get delay
   * @return delay
   **/
  @JsonProperty("delay")
  @ApiModelProperty(value = "")
  public Double getDelay() {
    return delay;
  }

  public void setDelay(Double delay) {
    this.delay = delay;
  }

  public LinkPath hop(Long hop) {
    this.hop = hop;
    return this;
  }

  /**
   * Get hop
   * @return hop
   **/
  @JsonProperty("hop")
  @ApiModelProperty(value = "")
  public Long getHop() {
    return hop;
  }

  public void setHop(Long hop) {
    this.hop = hop;
  }

  public LinkPath metric(Long metric) {
    this.metric = metric;
    return this;
  }

  /**
   * Get metric
   * @return metric
   **/
  @JsonProperty("metric")
  @ApiModelProperty(value = "")
  public Long getMetric() {
    return metric;
  }

  public void setMetric(Long metric) {
    this.metric = metric;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkPath linkPath = (LinkPath) o;
    return Objects.equals(this.path, linkPath.path) &&
        Objects.equals(this.delay, linkPath.delay) &&
        Objects.equals(this.hop, linkPath.hop) &&
        Objects.equals(this.metric, linkPath.metric);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, delay, hop, metric);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkPath {\n");

    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    delay: ").append(toIndentedString(delay)).append("\n");
    sb.append("    hop: ").append(toIndentedString(hop)).append("\n");
    sb.append("    metric: ").append(toIndentedString(metric)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

