/*
 * swagger说明文档　
 * 学习Swagger
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pml.sdsn.common.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Path
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2022-08-25T14:33:24.122+08:00")
public class Path {
  @JsonProperty("path")
  private List<String> path = null;

  @JsonProperty("wholePath")
  private List<Link> wholePath = null;

  @JsonProperty("delay")
  private Double delay = null;

  @JsonProperty("hop")
  private Long hop = null;

  @JsonProperty("metric")
  private Long metric = null;

  @JsonProperty("changeLink")
  private String changeLink = null;

  public Path path(List<String> path) {
    this.path = path;
    return this;
  }

  public Path addPathItem(String pathItem) {
    if (this.path == null) {
      this.path = new ArrayList<>();
    }
    this.path.add(pathItem);
    return this;
  }

  /**
   * Get path
   * @return path
   **/
  @JsonProperty("path")
  @ApiModelProperty(value = "")
  public List<String> getPath() {
    return path;
  }

  public void setPath(List<String> path) {
    this.path = path;
  }

  public Path wholePath(List<Link> wholePath) {
    this.wholePath = wholePath;
    return this;
  }

  public Path addWholePathItem(Link wholePathItem) {
    if (this.wholePath == null) {
      this.wholePath = new ArrayList<>();
    }
    this.wholePath.add(wholePathItem);
    return this;
  }

  /**
   * Get wholePath
   * @return wholePath
   **/
  @JsonProperty("wholePath")
  @ApiModelProperty(value = "")
  public List<Link> getWholePath() {
    return wholePath;
  }

  public void setWholePath(List<Link> wholePath) {
    this.wholePath = wholePath;
  }

  public Path delay(Double delay) {
    this.delay = delay;
    return this;
  }

  /**
   * Get delay
   * @return delay
   **/
  @JsonProperty("delay")
  @ApiModelProperty(value = "")
  public Double getDelay() {
    return delay;
  }

  public void setDelay(Double delay) {
    this.delay = delay;
  }

  public Path hop(Long hop) {
    this.hop = hop;
    return this;
  }

  /**
   * Get hop
   * @return hop
   **/
  @JsonProperty("hop")
  @ApiModelProperty(value = "")
  public Long getHop() {
    return hop;
  }

  public void setHop(Long hop) {
    this.hop = hop;
  }

  public Path metric(Long metric) {
    this.metric = metric;
    return this;
  }

  /**
   * Get metric
   * @return metric
   **/
  @JsonProperty("metric")
  @ApiModelProperty(value = "")
  public Long getMetric() {
    return metric;
  }

  public void setMetric(Long metric) {
    this.metric = metric;
  }

  public Path changeLink(String changeLink) {
    this.changeLink = changeLink;
    return this;
  }

  /**
   * Get changeLink
   * @return changeLink
   **/
  @JsonProperty("changeLink")
  @ApiModelProperty(value = "")
  public String getChangeLink() {
    return changeLink;
  }

  public void setChangeLink(String changeLink) {
    this.changeLink = changeLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Path path = (Path) o;
    return Objects.equals(this.path, path.path) &&
        Objects.equals(this.wholePath, path.wholePath) &&
        Objects.equals(this.delay, path.delay) &&
        Objects.equals(this.hop, path.hop) &&
        Objects.equals(this.metric, path.metric) &&
        Objects.equals(this.changeLink, path.changeLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, wholePath, delay, hop, metric, changeLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Path {\n");

    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    wholePath: ").append(toIndentedString(wholePath)).append("\n");
    sb.append("    delay: ").append(toIndentedString(delay)).append("\n");
    sb.append("    hop: ").append(toIndentedString(hop)).append("\n");
    sb.append("    metric: ").append(toIndentedString(metric)).append("\n");
    sb.append("    changeLink: ").append(toIndentedString(changeLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

