/*
 * vpn模型定义　
 * vpn模型
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pml.sdsn.common.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SRTunnel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2022-08-11T15:53:03.751+08:00")
public class SRTunnel {
  @JsonProperty("tunnelId")
  private Integer tunnelId = null;

  @JsonProperty("sourceSatellite")
  private String sourceSatellite = null;

  @JsonProperty("sourceSatelliteName")
  private String sourceSatelliteName = null;

  @JsonProperty("destSatellite")
  private String destSatellite = null;

  @JsonProperty("destSatelliteName")
  private String destSatelliteName = null;

  @JsonProperty("bandwidth")
  private Long bandwidth = null;

  @JsonProperty("delay")
  private Double delay = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("calcPolicy")
  private String calcPolicy = null;

  @JsonProperty("supportHsb")
  private Boolean supportHsb = null;
  

  @JsonProperty("telemetry")
  private Boolean telemetry = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    NORMAL("normal"),
    
    SWITCHED("switched"),
    
    DOWN("down");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("masterPath")
  private LinkPath masterPath = null;

  @JsonProperty("slavePath")
  private LinkPath slavePath = null;

  @JsonProperty("masterSrPath")
  private TunnelPath masterSrPath = null;

  @JsonProperty("slaveSrPath")
  private TunnelPath slaveSrPath = null;

  @JsonProperty("inFlow")
  private Double inFlow = null;

  @JsonProperty("outFlow")
  private Double outFlow = null;

  @JsonProperty("constraint")
  private Constraint constraint = null;

  public SRTunnel tunnelId(Integer tunnelId) {
    this.tunnelId = tunnelId;
    return this;
  }

  /**
   * Get tunnelId
   * @return tunnelId
   **/
  @JsonProperty("tunnelId")
  @ApiModelProperty(value = "")
  public Integer getTunnelId() {
    return tunnelId;
  }

  public void setTunnelId(Integer tunnelId) {
    this.tunnelId = tunnelId;
  }

  public SRTunnel sourceSatellite(String sourceSatellite) {
    this.sourceSatellite = sourceSatellite;
    return this;
  }

  /**
   * Get sourceSatellite
   * @return sourceSatellite
   **/
  @JsonProperty("sourceSatellite")
  @ApiModelProperty(value = "")
  public String getSourceSatellite() {
    return sourceSatellite;
  }

  public void setSourceSatellite(String sourceSatellite) {
    this.sourceSatellite = sourceSatellite;
  }

  public SRTunnel sourceSatelliteName(String sourceSatelliteName) {
    this.sourceSatelliteName = sourceSatelliteName;
    return this;
  }

  /**
   * Get sourceSatelliteName
   * @return sourceSatelliteName
   **/
  @JsonProperty("sourceSatelliteName")
  @ApiModelProperty(value = "")
  public String getSourceSatelliteName() {
    return sourceSatelliteName;
  }

  public void setSourceSatelliteName(String sourceSatelliteName) {
    this.sourceSatelliteName = sourceSatelliteName;
  }

  public SRTunnel destSatellite(String destSatellite) {
    this.destSatellite = destSatellite;
    return this;
  }

  /**
   * Get destSatellite
   * @return destSatellite
   **/
  @JsonProperty("destSatellite")
  @ApiModelProperty(value = "")
  public String getDestSatellite() {
    return destSatellite;
  }

  public void setDestSatellite(String destSatellite) {
    this.destSatellite = destSatellite;
  }

  public SRTunnel destSatelliteName(String destSatelliteName) {
    this.destSatelliteName = destSatelliteName;
    return this;
  }

  /**
   * Get destSatelliteName
   * @return destSatelliteName
   **/
  @JsonProperty("destSatelliteName")
  @ApiModelProperty(value = "")
  public String getDestSatelliteName() {
    return destSatelliteName;
  }

  public void setDestSatelliteName(String destSatelliteName) {
    this.destSatelliteName = destSatelliteName;
  }

  public SRTunnel bandwidth(Long bandwidth) {
    this.bandwidth = bandwidth;
    return this;
  }

  /**
   * Get bandwidth
   * @return bandwidth
   **/
  @JsonProperty("bandwidth")
  @ApiModelProperty(value = "")
  public Long getBandwidth() {
    return bandwidth;
  }

  public void setBandwidth(Long bandwidth) {
    this.bandwidth = bandwidth;
  }

  public SRTunnel delay(Double delay) {
    this.delay = delay;
    return this;
  }

  /**
   * Get delay
   * @return delay
   **/
  @JsonProperty("delay")
  @ApiModelProperty(value = "")
  public Double getDelay() {
    return delay;
  }

  public void setDelay(Double delay) {
    this.delay = delay;
  }

  public SRTunnel priority(Integer priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Get priority
   * @return priority
   **/
  @JsonProperty("priority")
  @ApiModelProperty(value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public SRTunnel calcPolicy(String calcPolicy) {
    this.calcPolicy = calcPolicy;
    return this;
  }

  /**
   * Get calcPolicy
   * @return calcPolicy
   **/
  @JsonProperty("calcPolicy")
  @ApiModelProperty(value = "")
  public String getCalcPolicy() {
    return calcPolicy;
  }

  public void setCalcPolicy(String calcPolicy) {
    this.calcPolicy = calcPolicy;
  }

  public SRTunnel supportHsb(Boolean supportHsb) {
    this.supportHsb = supportHsb;
    return this;
  }

  /**
   * Get supportHsb
   * @return supportHsb
   **/
  @JsonProperty("supportHsb")
  @ApiModelProperty(value = "")
  public Boolean isSupportHsb() {
    return supportHsb;
  }

  public void setSupportHsb(Boolean supportHsb) {
    this.supportHsb = supportHsb;
  }


  public SRTunnel telemetry(Boolean telemetry) {
    this.telemetry = telemetry;
    return this;
  }

  /**
   * Get telemetry
   * @return telemetry
   **/
  @JsonProperty("telemetry")
  @ApiModelProperty(value = "")
  public Boolean isTelemetry() {
    return telemetry;
  }

  public void setTelemetry(Boolean telemetry) {
    this.telemetry = telemetry;
  }

  public SRTunnel status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SRTunnel masterPath(LinkPath masterPath) {
    this.masterPath = masterPath;
    return this;
  }

  /**
   * Get masterPath
   * @return masterPath
   **/
  @JsonProperty("masterPath")
  @ApiModelProperty(value = "")
  public LinkPath getMasterPath() {
    return masterPath;
  }

  public void setMasterPath(LinkPath masterPath) {
    this.masterPath = masterPath;
  }

  public SRTunnel slavePath(LinkPath slavePath) {
    this.slavePath = slavePath;
    return this;
  }

  /**
   * Get slavePath
   * @return slavePath
   **/
  @JsonProperty("slavePath")
  @ApiModelProperty(value = "")
  public LinkPath getSlavePath() {
    return slavePath;
  }

  public void setSlavePath(LinkPath slavePath) {
    this.slavePath = slavePath;
  }

  public SRTunnel masterSrPath(TunnelPath masterSrPath) {
    this.masterSrPath = masterSrPath;
    return this;
  }

  /**
   * Get masterSrPath
   * @return masterSrPath
   **/
  @JsonProperty("masterSrPath")
  @ApiModelProperty(value = "")
  public TunnelPath getMasterSrPath() {
    return masterSrPath;
  }

  public void setMasterSrPath(TunnelPath masterSrPath) {
    this.masterSrPath = masterSrPath;
  }

  public SRTunnel slaveSrPath(TunnelPath slaveSrPath) {
    this.slaveSrPath = slaveSrPath;
    return this;
  }

  /**
   * Get slaveSrPath
   * @return slaveSrPath
   **/
  @JsonProperty("slaveSrPath")
  @ApiModelProperty(value = "")
  public TunnelPath getSlaveSrPath() {
    return slaveSrPath;
  }

  public void setSlaveSrPath(TunnelPath slaveSrPath) {
    this.slaveSrPath = slaveSrPath;
  }

  public SRTunnel inFlow(Double inFlow) {
    this.inFlow = inFlow;
    return this;
  }

  /**
   * Get inFlow
   * @return inFlow
   **/
  @JsonProperty("inFlow")
  @ApiModelProperty(value = "")
  public Double getInFlow() {
    return inFlow;
  }

  public void setInFlow(Double inFlow) {
    this.inFlow = inFlow;
  }

  public SRTunnel outFlow(Double outFlow) {
    this.outFlow = outFlow;
    return this;
  }

  /**
   * Get outFlow
   * @return outFlow
   **/
  @JsonProperty("outFlow")
  @ApiModelProperty(value = "")
  public Double getOutFlow() {
    return outFlow;
  }

  public void setOutFlow(Double outFlow) {
    this.outFlow = outFlow;
  }

  public SRTunnel constraint(Constraint constraint) {
    this.constraint = constraint;
    return this;
  }

  /**
   * Get constraint
   * @return constraint
   **/
  @JsonProperty("constraint")
  @ApiModelProperty(value = "")
  public Constraint getConstraint() {
    return constraint;
  }

  public void setConstraint(Constraint constraint) {
    this.constraint = constraint;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SRTunnel srTunnel = (SRTunnel) o;
    return Objects.equals(this.tunnelId, srTunnel.tunnelId) &&
        Objects.equals(this.sourceSatellite, srTunnel.sourceSatellite) &&
        Objects.equals(this.sourceSatelliteName, srTunnel.sourceSatelliteName) &&
        Objects.equals(this.destSatellite, srTunnel.destSatellite) &&
        Objects.equals(this.destSatelliteName, srTunnel.destSatelliteName) &&
        Objects.equals(this.bandwidth, srTunnel.bandwidth) &&
        Objects.equals(this.delay, srTunnel.delay) &&
        Objects.equals(this.priority, srTunnel.priority) &&
        Objects.equals(this.calcPolicy, srTunnel.calcPolicy) &&
        Objects.equals(this.supportHsb, srTunnel.supportHsb) &&
        Objects.equals(this.telemetry, srTunnel.telemetry) &&
        Objects.equals(this.status, srTunnel.status) &&
        Objects.equals(this.masterPath, srTunnel.masterPath) &&
        Objects.equals(this.slavePath, srTunnel.slavePath) &&
        Objects.equals(this.masterSrPath, srTunnel.masterSrPath) &&
        Objects.equals(this.slaveSrPath, srTunnel.slaveSrPath) &&
        Objects.equals(this.inFlow, srTunnel.inFlow) &&
        Objects.equals(this.outFlow, srTunnel.outFlow) &&
        Objects.equals(this.constraint, srTunnel.constraint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tunnelId, sourceSatellite, sourceSatelliteName, destSatellite, destSatelliteName, bandwidth, delay, priority, calcPolicy, supportHsb, telemetry, status, masterPath, slavePath, masterSrPath, slaveSrPath, inFlow, outFlow, constraint);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SRTunnel {\n");

    sb.append("    tunnelId: ").append(toIndentedString(tunnelId)).append("\n");
    sb.append("    sourceSatellite: ").append(toIndentedString(sourceSatellite)).append("\n");
    sb.append("    sourceSatelliteName: ").append(toIndentedString(sourceSatelliteName)).append("\n");
    sb.append("    destSatellite: ").append(toIndentedString(destSatellite)).append("\n");
    sb.append("    destSatelliteName: ").append(toIndentedString(destSatelliteName)).append("\n");
    sb.append("    bandwidth: ").append(toIndentedString(bandwidth)).append("\n");
    sb.append("    delay: ").append(toIndentedString(delay)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    calcPolicy: ").append(toIndentedString(calcPolicy)).append("\n");
    sb.append("    supportHsb: ").append(toIndentedString(supportHsb)).append("\n");
    sb.append("    telemetry: ").append(toIndentedString(telemetry)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    masterPath: ").append(toIndentedString(masterPath)).append("\n");
    sb.append("    slavePath: ").append(toIndentedString(slavePath)).append("\n");
    sb.append("    masterSrPath: ").append(toIndentedString(masterSrPath)).append("\n");
    sb.append("    slaveSrPath: ").append(toIndentedString(slaveSrPath)).append("\n");
    sb.append("    inFlow: ").append(toIndentedString(inFlow)).append("\n");
    sb.append("    outFlow: ").append(toIndentedString(outFlow)).append("\n");
    sb.append("    constraint: ").append(toIndentedString(constraint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

