/*
 * vpn模型定义　
 * vpn模型
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pml.sdsn.common.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TunnelPath
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2022-08-11T15:53:03.751+08:00")
public class TunnelPath {
  @JsonProperty("outInterface")
  private String outInterface = null;

  @JsonProperty("nextHop")
  private String nextHop = null;

  @JsonProperty("isMaster")
  private Boolean isMaster = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("labels")
  private List<Integer> labels = null;

  public TunnelPath outInterface(String outInterface) {
    this.outInterface = outInterface;
    return this;
  }

  /**
   * Get outInterface
   * @return outInterface
   **/
  @JsonProperty("outInterface")
  @ApiModelProperty(value = "")
  public String getOutInterface() {
    return outInterface;
  }

  public void setOutInterface(String outInterface) {
    this.outInterface = outInterface;
  }

  public TunnelPath nextHop(String nextHop) {
    this.nextHop = nextHop;
    return this;
  }

  /**
   * Get nextHop
   * @return nextHop
   **/
  @JsonProperty("nextHop")
  @ApiModelProperty(value = "")
  public String getNextHop() {
    return nextHop;
  }

  public void setNextHop(String nextHop) {
    this.nextHop = nextHop;
  }

  public TunnelPath isMaster(Boolean isMaster) {
    this.isMaster = isMaster;
    return this;
  }

  /**
   * Get isMaster
   * @return isMaster
   **/
  @JsonProperty("isMaster")
  @ApiModelProperty(value = "")
  public Boolean isIsMaster() {
    return isMaster;
  }

  public void setIsMaster(Boolean isMaster) {
    this.isMaster = isMaster;
  }

  public TunnelPath priority(Integer priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Get priority
   * @return priority
   **/
  @JsonProperty("priority")
  @ApiModelProperty(value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public TunnelPath labels(List<Integer> labels) {
    this.labels = labels;
    return this;
  }

  public TunnelPath addLabelsItem(Integer labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Get labels
   * @return labels
   **/
  @JsonProperty("labels")
  @ApiModelProperty(value = "")
  public List<Integer> getLabels() {
    return labels;
  }

  public void setLabels(List<Integer> labels) {
    this.labels = labels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TunnelPath tunnelPath = (TunnelPath) o;
    return Objects.equals(this.outInterface, tunnelPath.outInterface) &&
        Objects.equals(this.nextHop, tunnelPath.nextHop) &&
        Objects.equals(this.isMaster, tunnelPath.isMaster) &&
        Objects.equals(this.priority, tunnelPath.priority) &&
        Objects.equals(this.labels, tunnelPath.labels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outInterface, nextHop, isMaster, priority, labels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TunnelPath {\n");

    sb.append("    outInterface: ").append(toIndentedString(outInterface)).append("\n");
    sb.append("    nextHop: ").append(toIndentedString(nextHop)).append("\n");
    sb.append("    isMaster: ").append(toIndentedString(isMaster)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

