server:
  port: 8085
  jetty:
    threads:
      acceptors: 2
      selectors: 4
  servlet:
    path: /admin
spring:
  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 1
    ## Redis服务器地址
    host: ${REDIS_IP:localhost}
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: pml10
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/route?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    hikari:
      username: root
      password: 123456
  application:
    name: route #应用名称
  kafka:
    bootstrap-servers: ${KAFKA_IP:localhost}:${KAFKA_PORT:9092}
    consumer:
      auto-offset-reset: earliest #最早被消费的offset
      enable-auto-commit: false
      auto-commit-interval: 1s
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      batch-size: 1000
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 33554432
      acks: 1
    listener:
      concurrency: 1  #指定listener容器中的线程数，用于提高并发质量
      ack-mode: manual_immediate
    template:
      default-topic: producer #指定默认的topic
  flyway:
    enabled: true #是否开启
    validate-on-migrate: true # 迁移前校验 SQL 文件是否存在问题
    clean-disabled: true # 生产环境一定要关闭   是否要清除schema:表，索引，视图，存储过程.默认清理false  不清理-true
    check-location: true  # 校验路径下是否存在 SQL 文件
    baseline-on-migrate: true  # 最开始已经存在表结构，且不存在 flyway_schema_history 表时，需要设置为 true
    baseline-version: 0  # 基础版本 0
    locations: classpath:db/migration #默认路径
    table: flyway_schema_history #配置数据库信息表的名称

eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  eager-load:
    enabled: true
    clients: topology,pce

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pml.route.database
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


  # pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql
  
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include : "*"
